[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${ARB_SEPOLIA_RPC_URL}"

[etherscan]
sepolia={key="${ARBISCAN_API_KEY}",chainId=421614}